# Generated by Django 5.2.7 on 2025-11-27 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0002_alter_libro_contenido'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='leido',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='libro',
            name='contenido',
            field=models.TextField(max_length=200),
        ),
    ]
