# Generated by Django 5.2.7 on 2025-11-04 19:38

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('critica', '0001_initial'),
        ('libros', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='critica',
            options={'ordering': ['-created'], 'verbose_name': 'crítica', 'verbose_name_plural': 'críticas'},
        ),
        migrations.RemoveField(
            model_name='critica',
            name='id_libros',
        ),
        migrations.AddField(
            model_name='critica',
            name='libro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='criticas', to='libros.libro'),
        ),
        migrations.AddField(
            model_name='critica',
            name='puntuacion',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='critica',
            name='titulo',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='critica',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='criticas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='critica',
            name='contenido',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='critica',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
